# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20170521_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='List',
            new_name='list',
        ),
    ]
